### ISSUE TITLE
sf::st_transform(sf::st_crs(4326)) in dart_centroid()

### ISSUE THREAD

**Issue by choisy** [s3818311/dart#3]
I don't think we want `sf::st_transform(sf::st_crs(4326))` at the end of `dart_centroid()`

**Comment by s3818311** [comment]
I presume that the inputted geometry will be WSG84 (CRS:4326) so I figured that the users of this function would like the output to be WSG84 as well.

**Comment by choisy** [comment]
Well, I just think you restrict the possibilities there, so I would definitely remove it.

**Comment by s3818311** [comment]
So, you're suggesting that we projected with the new CRS, calculate the centroid, then return that centroid still in the projected CRS format, and the user will decide if they want to covert it back to WSG84 or not?

**Comment by choisy** [comment]
I think so, but please let me know if you don't think it's a good idea.

**Comment by s3818311** [comment]
I was looking over the usage of dart_centroid() in other places and I don't think this change will affect anything much as long as the CRS is consistent throughout.
I'm also thinking how about having a parameter for the output CRS then have it be the same as the target CRS if users don't specify it.
