### ISSUE TITLE
Remove if test in dart_max_dist()

### ISSUE THREAD

**Issue by choisy** [s3818311/dart#5]
I would remove the if test in the `dart_max_dist()` function has it has a huge computational cost. Furthermore I would replace the argument `with_centroid = FALSE` by `centroid` forcing the user to specify a column name of the geographical feature that contains centroid data.

**Comment by s3818311** [comment]
Hmm, I see. These changes wouldn't change the nature of the function much and quick to fix, I'll implement them asap.
